### PR TITLE
git checkout master

### PR DESCRIPTION
**Pull request by richerandprettier**
git checkout master
git merge --no-ff Bitcoin-QT-master
git push origin master

### CODE REVIEW

**Comment by richerandprettier** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

@richerandprettier @uvhw

**Comment by richerandprettier** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

#4

**Comment by richerandprettier** [comment]
> > git checkout master
> > git merge --no-ff Bitcoin-QT-master
> > git push origin master
> 
> #4

#2

**Comment by richerandprettier** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

#7

**Review by uvhw — CHANGES_REQUESTED** [review]
Ukraine Report - May 9th, 2022

Link: https://read.cash/@Gemstone/ukraine-report-may-9th-2022-edf90452

**Comment by uvhw** [comment]
> Ukraine Report - May 9th, 2022
> 
> Link: https://read.cash/@uvhw/ukraine-report-may-9th-2022-edf90452

**Comment by richerandprettier** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

#1

**Review by richerandprettier — COMMENTED** [review]
#4

**Review by uvhw — CHANGES_REQUESTED** [review]
#4

**Review by richerandprettier — COMMENTED** [review]
#10

**Comment by richerandprettier** [comment]
> #10

#8

**Comment by richerandprettier** [comment]
> #4

#10

**Comment by richerandprettier** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

#9

**Comment by richerandprettier** [comment]
> #2

#10

**Comment by richerandprettier** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

#7

**Comment by uvhw** [comment]
> git checkout master
> git merge --no-ff Bitcoin-QT-master
> git push origin master

#12

**Comment by uvhw** [comment]
> > git checkout master
> > git merge --no-ff Bitcoin-QT-master
> > git push origin master
> 
> #4

#12

**Review by uvhw — COMMENTED** [review]
#7

**Pull request closed without merging**
